# Jekyll
name: Maya Hanyu
description: Software Engineer
favicon:
  path: assets/images/favicon.png
  type: png
logo: https://avatars.githubusercontent.com/u/17304731
url: https://mhanyu.github.io
badge:
  enable: false

# Defaults
defaults:
  -
    scope:
      path: "*.html"
    values:
      layout: "default"
  -
    scope:
      path: "assets/files"
    values:
      file: true

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile]
