# Jekyll
theme: linkhub-jekyll-theme
name: Maya Hanyu
description: Software Engineer

badge:
  enable: false

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile]
